// <auto-generated />
using System;
using ArmaReforger.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Project1.Migrations
{
    [DbContext(typeof(ArmaReforgerDbContext))]
    [Migration("20250925143907_AddServerRecordCompositeKey")]
    partial class AddServerRecordCompositeKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArmaReforger.Models.PlayerIpAddress", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("ipAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("playerRecordbiIdentity")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("playerRecordbiIdentity");

                    b.ToTable("playerIpAddresses");
                });

            modelBuilder.Entity("ArmaReforger.Models.PlayerName", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("playerRecordBiIdentity")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("playerRecordBiIdentity");

                    b.ToTable("playerNames");
                });

            modelBuilder.Entity("ArmaReforger.Models.PlayerRecord", b =>
                {
                    b.Property<string>("biIdentity")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("biIdentity");

                    b.ToTable("playerRecords");
                });

            modelBuilder.Entity("ArmaReforger.Models.ServerPlayerConnection", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("connectionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("playerRecordbiIdentity")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("serverRecordid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("playerRecordbiIdentity");

                    b.HasIndex("serverRecordid");

                    b.ToTable("serverPlayerConnections");
                });

            modelBuilder.Entity("ArmaReforger.Models.ServerRecord", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("ipAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("port")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("ipAddress", "port")
                        .IsUnique();

                    b.ToTable("serverRecords");
                });

            modelBuilder.Entity("ArmaReforger.Models.PlayerIpAddress", b =>
                {
                    b.HasOne("ArmaReforger.Models.PlayerRecord", "playerRecord")
                        .WithMany()
                        .HasForeignKey("playerRecordbiIdentity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("playerRecord");
                });

            modelBuilder.Entity("ArmaReforger.Models.PlayerName", b =>
                {
                    b.HasOne("ArmaReforger.Models.PlayerRecord", "playerRecord")
                        .WithMany()
                        .HasForeignKey("playerRecordBiIdentity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("playerRecord");
                });

            modelBuilder.Entity("ArmaReforger.Models.ServerPlayerConnection", b =>
                {
                    b.HasOne("ArmaReforger.Models.PlayerRecord", "playerRecord")
                        .WithMany()
                        .HasForeignKey("playerRecordbiIdentity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArmaReforger.Models.ServerRecord", "serverRecord")
                        .WithMany()
                        .HasForeignKey("serverRecordid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("playerRecord");

                    b.Navigation("serverRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
