// <auto-generated />
using System;
using ArmaReforger.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Project1.Migrations
{
    [DbContext(typeof(ArmaReforgerDbContext))]
    [Migration("20250925173953_UpdatedModelsAndColumnNames")]
    partial class UpdatedModelsAndColumnNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArmaReforger.Models.PlayerIpAddressModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("biIdentity")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("bi_identity");

                    b.Property<string>("ipAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ip_address");

                    b.HasKey("id");

                    b.HasIndex("biIdentity", "ipAddress")
                        .IsUnique();

                    b.ToTable("playerIpAddresses");
                });

            modelBuilder.Entity("ArmaReforger.Models.PlayerNameModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("biIdentity")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("bi_identity");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("name");

                    b.HasKey("id");

                    b.HasIndex("biIdentity", "name")
                        .IsUnique();

                    b.ToTable("playerNames");
                });

            modelBuilder.Entity("ArmaReforger.Models.PlayerRecordModel", b =>
                {
                    b.Property<string>("biIdentity")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("bi_identity");

                    b.HasKey("biIdentity");

                    b.ToTable("playerRecords");
                });

            modelBuilder.Entity("ArmaReforger.Models.ServerPlayerConnectionModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("action");

                    b.Property<string>("biIdentity")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("bi_identity");

                    b.Property<DateTime>("connectionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("connection_time");

                    b.Property<int>("server_id")
                        .HasColumnType("int")
                        .HasColumnName("server_id");

                    b.HasKey("id");

                    b.HasIndex("biIdentity");

                    b.HasIndex("server_id");

                    b.ToTable("serverPlayerConnections");
                });

            modelBuilder.Entity("ArmaReforger.Models.ServerRecordModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("ipAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ip_address");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int>("port")
                        .HasColumnType("int")
                        .HasColumnName("port");

                    b.HasKey("id");

                    b.HasIndex("ipAddress", "port")
                        .IsUnique();

                    b.ToTable("serverRecords");
                });

            modelBuilder.Entity("ArmaReforger.Models.PlayerIpAddressModel", b =>
                {
                    b.HasOne("ArmaReforger.Models.PlayerRecordModel", "playerRecord")
                        .WithMany()
                        .HasForeignKey("biIdentity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("playerRecord");
                });

            modelBuilder.Entity("ArmaReforger.Models.PlayerNameModel", b =>
                {
                    b.HasOne("ArmaReforger.Models.PlayerRecordModel", "playerRecord")
                        .WithMany()
                        .HasForeignKey("biIdentity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("playerRecord");
                });

            modelBuilder.Entity("ArmaReforger.Models.ServerPlayerConnectionModel", b =>
                {
                    b.HasOne("ArmaReforger.Models.PlayerRecordModel", "playerRecord")
                        .WithMany()
                        .HasForeignKey("biIdentity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArmaReforger.Models.ServerRecordModel", "serverRecord")
                        .WithMany()
                        .HasForeignKey("server_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("playerRecord");

                    b.Navigation("serverRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
